### ISSUE TITLE
ACTIVITIES

### ISSUE THREAD

**Issue by dofbi** [AfricTivistes/charter-portal-issues#15]

**Comment by cissengary** [comment]
Cc @dofbi 

**1- CIVIC TECH FUND AFRICA** 

**Texte descriptif** 

Le Civic Tech Fund Africa vise à soutenir les organisations locales qui utilisent des solutions technologiques dans les pays cibles du projet...

**Texte interne** 

L' objectif principal de ce mécanisme de subvention est de faciliter la participation active des organisations civiques en particulier les initiatives basées sur la jeunesse dans le Charter Project Africa. Le mécanisme vise à soutenir les organisations locales dans les pays ciblés afin qu'elles aient la capacité de jouer un rôle dans l'utilisation des solutions technologiques et de s'engager dans les initiatives AGA. 

Le Civic Tech Fund Africa est conçu dans le contexte du Charter Project Africa, Il intègre en outre le Fonds Civic Tech de l'Union africaine, hébergé par l'Union africaine. Le Charter Project Africa et le Fonds pour la technologie civique de l'Union africaine partagent des objectifs communs et, en particulier, mettent tous deux l'accent sur l'utilisation de la citoyenneté technologique pour améliorer la prise de décision publique inclusive et renforcer la gouvernance démocratique dans toute l'Afrique. 

La Civic Tech ou technologie civique, décrit une technologie qui renforce l'engagement des citoyens et renforce la responsabilité et la transparence des processus de gouvernance et des services publics. Une technologie civique efficace est souvent le résultat d'une collaboration entre la société civile, les pouvoirs publics et le secteur privé. Elle peut également inclure un fort engagement numérique, en ce sens qu'elle utilise des outils pour soutenir le fonctionnement des réseaux et plates-formes publics, l'engagement des citoyens ou des campagnes de défense de l'intérêt public.

En savoir plus: https://civictechfund.africa/fr/

**ENG**


**Descriptive text** 

The Civic Tech Fund Africa aims to support local organisations using technology solutions in the project's target countries...

**On-site text** 

The main objective of this grant mechanism is to facilitate the active participation of civic organisations, particularly youth-based initiatives, in the Charter Project Africa. The mechanism aims to support local organisations in the target countries to have the capacity to play a role in the use of technology solutions and to engage in AGA initiatives. 

The Civic Tech Fund Africa is designed in the context of the Charter Project Africa, and also incorporates the African Union Civic Tech Fund, hosted by the African Union. The Charter Project Africa and the African Union Civic Tech Fund share common objectives and, in particular, both focus on the use of technological citizenship to improve inclusive public decision-making and strengthen democratic governance across Africa. 

Civic Tech, or civic technology, describes technology that enhances citizen engagement and strengthens the accountability and transparency of governance processes and public services. Effective civic technology is often the result of collaboration between civil society, government and the private sector. It can also include strong digital engagement, in that it uses tools to support the operation of public networks and platforms, citizen engagement or public interest campaigns.

More, here: https://civictechfund.africa/en/

**Comment by cissengary** [comment]
Cc @dofbi 

**MOOC DEG** 

**Texte descriptif** 

Le MOOC DEG fournit des contenus pédagogiques et didactiques sur la démocratie, la bonne gouvernance et les élections en Afrique...

**Texte interne**

Le MOOC “Démocratie et Gouvernance en Afrique” (MOOC DEG) vise à pallier le déficit d’informations, les difficultés d’accès aux contenus institutionnels et les biais de traitement des médias. Ainsi, le programme cible les jeunes, les acteurs de la société civile, des acteurs et professionnels des médias, des responsables de l’administration publique (centrale ou locale).

Ce programme d'enseignement à distance a pour objectif de fournir des contenus pédagogiques et didactiques sur la démocratie, la bonne gouvernance et les élections en Afrique. Il constitue une réponse à une demande de plus en plus forte de maîtrise des notions suscitées.

Le MOOC DEG est mise en œuvre par l’organisation AfricTivistes dans le cadre du projet The Charter Project Africa. Ces cours en ligne sont dispensés aux bénéficiaires en étroite conformité avec les objectifs de la Charte africaine pour la démocratie, les Élections et la Gouvernance (CADEG) et du projet.

Pour en savoir plus: https://mooc.charter.africa/

**ENG** 

**Descriptive text** 

The DEG MOOC provides pedagogical and didactic content on democracy, good governance and elections in Africa...

**On-site text**

The MOOC "Democracy and Governance in Africa" aims to overcome the information deficit, the difficulties of access to institutional content and the bias of the media. Thus, the programme targets young people, civil society actors, media actors and professionals, public administration officials (central or local).

The objective of the distance learning programme is to provide pedagogical and didactic content on democracy, good governance and elections in Africa. It is a response to a growing demand for mastery of the concepts involved.

The "Democracy, Elections and Governance in Africa" distance learning programme is implemented by AfricTivistes as part of the Charter Project Africa. These online courses are delivered to beneficiaries in close alignment with the objectives of the ACDEG and the Charter Project Africa.

More, here: https://mooc.charter.africa/en_GB

**Comment by cissengary** [comment]
Cc @dofbi 

**ACDEG PRIMER** 

**Texte descriptif** 

Dans le cadre du 15e anniversaire de la CADEG, ECDPM a conçu un guide en ligne qui contient tout ce qu'il faut savoir sur la Charte: c'est qu'est la CADEG, comment elle s'inscrit dans un agenda africain controversé mais important en même temps, et où les organisations de la société civile s'inscrivent dans la mise en pratique de cette charte...

**Texte interne**

Les récents coups d'État militaires et les manipulations constitutionnelles ont attiré l'attention sur la question de la gouvernance dans les pays africains, et sur ce qui peut être fait pour l'améliorer. L'Union africaine (UA) joue un rôle dans la mise en place de cadres normatifs en matière de gouvernance en Afrique et s'appuie sur divers documents juridiques et politiques adoptés par ses États membres pour jouer ce rôle. L'UA rejette les changements anticonstitutionnels de gouvernement et les États membres qui enfreignent cette norme s'exposent à des sanctions, telles que la suspension de leur adhésion à l'UA. Mais ces mesures ne sont pas systématiquement prises. Quelles sont les règles qui déterminent si et comment l'UA tente de faire respecter ces normes ? Et comment les traités internationaux et continentaux peuvent-ils contribuer à améliorer la gouvernance et la responsabilité de la base au sommet ?

Dans ce guide, vous apprendrez davantage sur l'instrument le plus important qui définit ce programme de gouvernance continentale : la Charte africaine de la démocratie, des élections et de la gouvernance (CADEG). Elle décrit les principales règles qui s'appliquent aux États et leur responsabilité envers leurs citoyens sur une série de questions politiques, économiques et sociales liées à la gouvernance. Nous examinons ici ce qu'est la CADEG et comment elle s'inscrit dans ce programme de gouvernance africain controversé mais plus important, quelle est la place des organisations de la société civile dans la réalisation pratique de cette instrument de l'UA qu'est la CADEG. 

Pour en savoir plus : https://ecdpm.org/fr/publications/comprendre-la-charte-africaine-de-la-democratie-des-elections-et-de-la-gouvernance/

**ENG**

**Descriptive text**

As part of the 15th anniversary of the CADEG, ECDPM has developed an online guide that contains everything you need to know about the Charter: what the CADEG is, how it fits into a controversial but important African agenda, and where civil society organisations fit into the implementation of the Charter...

**On-site text**

Recent military coups and constitutional manipulation have drawn attention to the issue of governance in African countries, and what can be done to improve it. The African Union (AU) plays a role in setting normative frameworks around governance in Africa and it relies on various legal and policy documents agreed on by its member states to play that role. The AU for example rejects unconstitutional changes of government and member states that breach this norm can face sanctions, such as suspensions of membership from the AU. But such actions are not consistently taken. What are the rules that shape if and how the AU tries to enforce such norms? And how can international and continental treaties help improve governance and accountability from the bottom up?

In this guide, you can learn about the most prominent instrument that defines this continental governance agenda: the African Charter on Democracy, Elections and Governance (ACDEG), which turns 15 in early 2022. It outlines the main rules that apply to states and their responsibility towards their citizens on a range of political, economic and social issues pertaining to governance. Here we look into what it is, how it fits in this controversial but important African governance agenda, and where civil society organisations fit when it comes to the realisation of the ACDEG in practice.

More, here: https://ecdpm.org/publications/guide-african-charter-democracy-elections-governance/

**Comment by cissengary** [comment]
Cc @dofbi 

Please de ne pas oublier de revoir les icones 

![Charter 3](https://user-images.githubusercontent.com/84854916/167420628-ae259253-2eaa-401d-b972-bfe4014e1bcd.PNG)

**Comment by dofbi** [comment]
Salaam grand @cissengary 
Bien reçus dés que j'update je te send le lien pour vérifie
Merci

**Comment by cissengary** [comment]
> Salaam grand @cissengary Bien reçus dés que j'update je te send le lien pour vérifie Merci

Salaam @dofbi ok c'est noté

**Comment by dofbi** [comment]
Salaam @cissengary 
Activités done

![Capture d’écran du 2022-05-16 09-11-03](https://user-images.githubusercontent.com/84446/168559390-8f5885ba-e053-49dc-a313-a31e829ae64f.png)

Posibiliité update dans l'espace admin

![Capture d’écran du 2022-05-16 09-13-56](https://user-images.githubusercontent.com/84446/168559703-36394685-a05a-44eb-959c-a20216cabf50.png)

**Comment by cissengary** [comment]
> Salaam @cissengary Activités done
> 
> ![Capture d’écran du 2022-05-16 09-11-03](https://user-images.githubusercontent.com/84446/168559390-8f5885ba-e053-49dc-a313-a31e829ae64f.png)
> 
> Posibiliité update dans l'espace admin
> 
> ![Capture d’écran du 2022-05-16 09-13-56](https://user-images.githubusercontent.com/84446/168559703-36394685-a05a-44eb-959c-a20216cabf50.png)

**Comment by cissengary** [comment]
Salam @dofbi j'espère que tu vas bien. Je voudrais te rappeler de mettre le lien dans la partie **Civic Tech Fund** 

![CTF](https://user-images.githubusercontent.com/84854916/168793888-71833fb0-785a-4850-af4e-222405a1b87e.PNG)
