### ISSUE TITLE
Modele de page pour l'evenement en anglais✨

### ISSUE THREAD

**Issue by adrianadauria** [AfricTivistes/charter-portal-issues#18]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/AfricTivistes/charter-portal-issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby.

### Pain

Bonjour, 
comme requis, voilà un doc google avec le modèle de la page a creer pour l'evenement dont on a parlé la semaine passé

https://docs.google.com/document/d/1ruUKlsUsnQsQnGXQw-rkq-tRCYvAzz-k78Ura8JoqGU/edit?usp=sharing 

### Suggested Solution

https://docs.google.com/document/d/1ruUKlsUsnQsQnGXQw-rkq-tRCYvAzz-k78Ura8JoqGU/edit?usp=sharing

### Tasks

- [ ] ...
- [ ] ...
...

**Comment by dofbi** [comment]
Bien reçu @adrianadauria 👍🏾
