### ISSUE TITLE
 Modele de page pour l'evenement en français✨

### ISSUE THREAD

**Issue by adrianadauria** [AfricTivistes/charter-portal-issues#19]
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/AfricTivistes/charter-portal-issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby.

### CC

Hi

### Pain

Chers tous, 
voici le modèle en google doc pour la version de la page en français. Merci encore pour votre collaboration. 

https://docs.google.com/document/d/1Bbz04ZhsgSua9huPWmWRX3ZcgMFeQID9lxZDVRYMaHI/edit 

### Suggested Solution

https://docs.google.com/document/d/1Bbz04ZhsgSua9huPWmWRX3ZcgMFeQID9lxZDVRYMaHI/edit 

### Tasks

- [ ] ...
- [ ] ...
...

**Comment by cissengary** [comment]
Cc @dofbi
